[package]
name = "mactype"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rdev = "0.5.3"
strum = "0.26"
strum_macros = "0.26"
enigo = "0.0.14"